apiVersion: v1
kind: Service
metadata:
  name: rls1-hello-world-lb
  namespace: vault2
  labels:
    app.kubernetes.io/instance: rls1
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hello-world
  annotations:
    # Optional: Forces GCP to provision a Regional External Layer 4 Network Load Balancer (recommended)
    cloud.google.com/l4-rxlb: "true" 
spec:
  type: LoadBalancer
  selector:
    # These must exactly match the labels under spec.template.metadata.labels in your deployment
    app.kubernetes.io/instance: rls1
    app.kubernetes.io/name: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80         # The port the external load balancer will listen on
    targetPort: 80   # The containerPort your Nginx application is listening on
